### ISSUE TITLE
Extending the reference tracking algorithm

### ISSUE THREAD

**Issue by dplyukhin** [dplyukhin/UIGC#12]
In order to implement closed set detection (#7) we need to change how actors keep track of references.

## Deliverables

- [x] **Implement knowledge sets:** A knowledge set is a snapshot of the references an actor knows about at a given time. This includes `ctx.refs`, `ctx.created`, and `ctx.owners`. 

- [x] **Implement knowledge set tests.** These will be useful for the other modifications we make.

- [x] **Release acknowledgment messages:** Suppose `ref = gc.ActorRef(x,A,B)`. If A invokes `ctx.release(ref)`, that reference should remain in its knowledge set until after it receives a corresponding `AckRelease` message from B. Bugs to watch out for:
  - Make sure actors cannot release a reference multiple times. You can do this by moving the reference from `ctx.refs` to a new temporary set, `ctx.releasing_refs`.
  - Suppose A sent B a `Release` message containing reference `x` and then immediately sent B another `Release` message containing reference `y`. Then A will receive two `AckRelease` messages in response. Make sure A does not forget `y` until the _second_ `AckRelease message. You can do this by attaching a sequence number to every `Release` and `AckRelease` message.

- [x] **Implement acknowledgment tests:** Look at knowledge sets to make sure that the invariant above is maintained.
