### ISSUE TITLE
Modified reference tracking testing

### ISSUE THREAD

**Issue by chasminimus** [dplyukhin/UIGC#19]
With the reference tracking algorithm changed, we need some testing changes as well:

- [x] Modify the snapshot test to be more robust, test message counts and `released_owners` and maybe the specifics of the creation map
- [x] Test that `release` processes the correct references. Create a protocol where A spawns B and C. Then A sends B two references _x_, _y_ : B⊸C. Then B spawns D, and creates _w_: D⊸C using _x_ and creates _z_: D⊸C using _y_. Then B releases _x_. Its state should no longer contain _x_ or _w_.
- [x] Test that message counts are properly destroyed at the right moments. Send counts should be destroyed when those references are released and receive counts should be destroyed when handling a release.
