### ISSUE TITLE
Fault-tolerant reference tracking

### ISSUE THREAD

**Issue by dplyukhin** [dplyukhin/UIGC#4]
I can see a few problematic ways that our reference tracking scheme interacts with Akka's supervision hierarchy:
1. If an actor throws an exception, all its references are lost. Depending on the fault-handling strategy, we may want to do different things:
  - If the actor is restarted with its previous state, then this behavior is (probably?) fine.
  - If the actor is not restarted, we should release all its references. Can we use some sort of hook?
2. When a supervisor terminates, an Akka signal causes its children to terminate. What should happen if there are unreleased references to that child? At the very least, the child should release all its references before terminating.

Deliverables:
- [ ] A report of how Akka's fault handling interacts with reference tracking
- [ ] Bug fixes to handle those cases better than we currently do
- [ ] Test cases to check that the behavior is as expected
